spring:
  application:
    name: cadastrodeninjas

  h2:
    console.enabled: true

  datasource:
    url: ${DATABASE_URL}
    DB_CLOSE_DELAY: -1
    DB_CLOSE_ON_EXIT: FALSE
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver: org.h2.Driver

  # JPA/HIBERNATES configuration
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

