spring:
  application:
    name: cadastrodeninjas

  h2:
    console.enabled: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver: org.h2.Driver

  # JPA/HIBERNATES configuration
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

  # flyway configuration
  flyway:
    enable: true
    locations: classpath:db/migrations
    baseline-on-migrate: true

  # mvc configuration
  mvc:
    hiddenmethod:
      filter.enabled: true
